### ISSUE TITLE
TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.

### ISSUE THREAD

**Issue by marko-asplund** [http4s/http4s#2253]
I get the following error message in the log with http4s v0.20.0-M2. This doesn't occur with 0.18.19.
Not sure if this is related to http4s client or server.
The error message looks the same as with #2156, but this still happens with M2.

```
2018-11-06 21:41:53.255 [blaze-selector-0-2] ERROR o.h.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
```

**Comment by rossabaker** [comment]
That's the server.  We just fixed a variant of this in M2, but there could be more.

- What is your server config?
- What client did you use?
- Does it actually time out a request, or is this happening in the background?
- Do you have a reproducible example?  This will make it easier to chase.

**Comment by marko-asplund** [comment]
1.
```
 BlazeBuilder[F]
        .bindHttp(Port, BindAddress)
        .mountService(CORS(`no-cache`(myRestService())), prefix = "/api/foo")
        .serve
```
2. 
```
Http1Client.stream[F](HttpClientConfig).map { c =>
org.http4s.client.middleware.Logger(true, true)(c)
}
```
3. it appears that no requests actually time out
4. unfortunately, not ATM

**Comment by marko-asplund** [comment]
Here's a full log extract with slightly more info from just now:
```
2018-11-10 10:39:16.064 [blaze-selector-0-1] ERROR o.h.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
2018-11-10 10:39:16.072 [blaze-selector-0-1] ERROR o.h.s.blaze.Http1ServerStage$$anon$1 - Fatal Error: Error in requestLoop()
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
2018-11-10 10:39:16.074 [blaze-selector-0-1] ERROR o.h.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
```

**Comment by BenShaw** [comment]
If it helps I was getting this error until I updated to 0.20.0-M3 after which it dissapeared

**Comment by jchampemont** [comment]
Hi,

I'm on M3 and and I still have this issue.

Using this repo: https://github.com/jchampemont/http4s-2253

When I do a simple GET request to the `/_health` endpoint (from Insomnia REST client or Firefox) everything goes well. And then 30s later the previously mentioned stacktrace is logged to the server.

Here is a more complete log extract:

```
2018-11-15 13:52:18,948 blaze-selector-0-0 TraceId= [INFO] NIO1SocketServerGroup : Accepted connection from /172.17.0.1:51488
2018-11-15 13:52:49,169 blaze-selector-0-0 TraceId= [ERROR] NIO1HeadStage : Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
2018-11-15 13:52:49,171 blaze-selector-0-0 TraceId= [ERROR] Http1ServerStage$$anon$1 : Fatal Error: Error in requestLoop()
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
2018-11-15 13:52:49,171 blaze-selector-0-0 TraceId= [ERROR] NIO1HeadStage : Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
```

**Comment by rossabaker** [comment]
It doesn't happen on `Ok("pong")` but it does on `Ok()`.  That's a big clue.

**Comment by rossabaker** [comment]
False observation above.

I can reproduce this on the example project but not on the examples-blaze in the repo.  I haven't identified the difference yet.

**Comment by rossabaker** [comment]
This code is still using `BlazeBuilder,` which we deprecated in favor of `BlazeServerBuilder` to distinguish it better from the client, but we failed to deprecate the companion object.  The idle timeout implementation changed in `BlazeServerBuilder`, but not in the deprecated `BlazeBuilder`.  A workaround is to use `BlazeServerBuilder`.  Deprecation and a fix is coming.

**Comment by jchampemont** [comment]
My bad! Thanks, I'll use `BlazeServerBuilder` then.

**Comment by rossabaker** [comment]
Nope, we didn't deprecate it properly.  Sorry for the problem.  #2285 should prevent it from happening to anyone else.

**Comment by marko-asplund** [comment]
@rossabaker So, for the repro code, the workaround would be as follows, right?

https://github.com/marko-asplund/http4s020-timeout/commit/d3ef8bf6434e6024af0f831fa90eb7362bb21ffa

Looks like there won't be anything like `mountService` prefix in 0.20, will there?
I think it was rather useful when having multiple distinct resources in your REST API and you wanted to make sure there won't be any conflicts with the resource paths they handle.

**Comment by rossabaker** [comment]
@marko-asplund Do you find the new way worse than combining `HttpRoutes` in a `Router`?  We felt that multiple `mountService` calls made a bit more sense in a servlet context than they did in blaze, but I'm happy to entertain arguments otherwise.  It might be better as a separate RFC issue.

**Comment by rossabaker** [comment]
Believe this is fixed in `BlazeServerBuilder`.  Please reopen if not.
